### ISSUE TITLE
import statement fails

### ISSUE THREAD

**Issue by durack1** [PCMDI/nominal_resolution#7]
```python
(nomRes) duro@ocean:[durolib]:[issue27]:[12577]> python
Python 3.6.6 | packaged by conda-forge | (default, Jul 26 2018, 09:53:17)
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import nominal_resolution
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "anaconda2/envs/nomRes/lib/python3.6/site-packages/nominal_resolution/__init__.py", line 1, in <module>
    from api import mean_resolution, nominal_resolution  # noqa
ModuleNotFoundError: No module named 'api'
```

**Comment by doutriaux1** [comment]
nice! I wonder how come the test suite passes? Will fix promptly.

**Comment by doutriaux1** [comment]
should be `.api` but still why does it now work....

**Comment by doutriaux1** [comment]
which conda package? nightly or master?

**Comment by durack1** [comment]
```
ls anaconda2/envs/nomRes/conda-meta/*cdat*
anaconda2/envs/nomRes/conda-meta/cdat_info-8.0.2018.07.12.00.12.g4ac9fae-py36_0.json
```

**Comment by doutriaux1** [comment]
???
I need 
`conda list nomin`
This looks like a very old one. Please update.

**Comment by doutriaux1** [comment]
yes old version, please update to yesterday

**Comment by durack1** [comment]
@doutriaux1 is this expected?
```
(nomRes) duro@ocean:[durolib]:[issue27_durack1_InvalidComponentTime]:[12508]> conda update nominal_resolution
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.5.10
  latest version: 4.5.11

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /anaconda2/envs/nomRes

  added / updated specs:
    - nominal_resolution


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    certifi-2018.8.24          |           py36_1         140 KB
    openssl-1.0.2p             |       h14c3975_0         3.5 MB
    ------------------------------------------------------------
                                           Total:         3.6 MB

The following packages will be UPDATED:

    certifi:         2018.8.24-py36_1     conda-forge --> 2018.8.24-py36_1
    openssl:         1.0.2o-h470a237_1    conda-forge --> 1.0.2p-h14c3975_0

The following packages will be DOWNGRADED:

    ca-certificates: 2018.8.24-ha4d7672_0 conda-forge --> 2018.03.07-0
```

**Comment by doutriaux1** [comment]
yes they updated their conda

**Comment by durack1** [comment]
@doutriaux1 sorry I should have been more clear, according to the above I am up-to-date for `nominal_resolution`

**Comment by durack1** [comment]
@doutriaux1 
```(nomRes) duro@ocean:[durolib]:[issue27_durack1_InvalidComponentTime]:[12509]> conda update -c pcmdi/label/nightly -c cdat nominal_resolution
Solving environment: done
==> WARNING: A newer version of conda exists. <==
  current version: 4.5.10
  latest version: 4.5.11
Please update conda by running
    $ conda update -n base -c defaults conda
## Package Plan ##
  environment location: /anaconda2/envs/nomRes
  added / updated specs:
    - nominal_resolution
The following packages will be downloaded:
    package                    |            build
    ---------------------------|-----------------
    nominal_resolution-1.0.2018.08.29.14.09.gdede29a|           py36_0           7 KB  pcmdi/label/nightly
The following packages will be UPDATED:
    nominal_resolution: 1.0.2018.08.24.01.10.g36c4a6c-py36_0 pcmdi/label/nightly --> 1.0.2018.08.29.14.09.gdede29a-py36_0 pcmdi/label/nightly
```
Will try this now

**Comment by doutriaux1** [comment]
@durack1 ok so the new version should be good now. correct?

**Comment by durack1** [comment]
Doh! @doutriaux1 it doesn't appear so
```python
(nomRes) duro@ocean:[durolib]:[issue27_durack1_InvalidComponentTime]:[9974]> python
Python 3.6.6 | packaged by conda-forge | (default, Jul 26 2018, 09:53:17)
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import nominal_resolution
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda2/envs/nomRes/lib/python3.6/site-packages/nominal_resolution/__init__.py", line 1, in <module>
    from api import mean_resolution, nominal_resolution  # noqa
ModuleNotFoundError: No module named 'api'
>>>

(nomRes) durack1@oceanonly:[durolib]:[issue27_durack1_InvalidComponentTime]:[9974]> ls /anaconda2/envs/nomRes/conda-meta/*nomin*
anaconda2/envs/nomRes/conda-meta/nominal_resolution-1.0.2018.08.29.14.09.gdede29a-py36_0.json
```

**Comment by durack1** [comment]
@doutriaux1 this should get you most of the way to both atm and ocn variable tests

[nomResTest-180829.py.txt](https://github.com/PCMDI/nominal_resolution/files/2334211/nomResTest-180829.py.txt)

**Comment by durack1** [comment]
@doutriaux1 for completeness, the latest `nightly` works:
```python
(nomRes) duro@ocean:[durolib]:[issue27_durack1_InvalidComponentTime]:[9941]> python
Python 3.6.6 | packaged by conda-forge | (default, Jul 26 2018, 09:53:17)
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import nominal_resolution
>>>
(nomRes) durack1@oceanonly:[durolib]:[issue27_durack1_InvalidComponentTime]:[9941]> ls /anaconda2/envs/nomRes/conda-meta/*nomin*
/anaconda2/envs/nomRes/conda-meta/nominal_resolution-1.0.2018.08.30.00.21.gde863bc-py36_0.json
```
